### ISSUE TITLE
Package Version Updates

### ISSUE THREAD

**Issue by DerekTBrown** [bsliran/angular2-meteor-base#23]
The point of a boilerplate is to provide a minimal installation.  This example provides a lot of extraneous code:
- [x] [Remove JQuery](https://github.com/bsliran/angular2-meteor-base/blob/master/.meteor/packages#L11)
  What is the point of using Angular2 if you are going to include JQuery?
- [x] [Set Version for Angular2 Compilers](https://github.com/bsliran/angular2-meteor-base/blob/master/.meteor/packages#L21)
  Recent changes in 0.6.0 are breaking for some users.  Specify to 0.5.7
- [ ] [Remove Mocha Dependencies](https://github.com/bsliran/angular2-meteor-base/blob/master/.meteor/packages#L26)
  This isn't a core component of Angular2Meteor

**Comment by dotansimha** [comment]
The angular2-compilers issues fixed in 0.6.1.

**Comment by dotansimha** [comment]
Removed jQuery and everything seems fine.

**Comment by dotansimha** [comment]
@DerekTBrown thanks for helping! 
I fixed 2 of 3 you mentioned, but note that the Mocha issue does not have any solution. 
Mocha is not part of Angular2-Meteor, that's correct, and that's why Mocha isn't a dependency of Angular2-Meteor. We use Mocha in this boilerplate to provide an easy example for client side tests of Angular2-Meteor applications. 

Please re-open if you have another idea regarding the tests issue. 

Thanks!
