### ISSUE TITLE
scss main file should be in /client

### ISSUE THREAD

**Issue by Devidian** [bsliran/angular2-meteor-base#34]
Hi, just started a project 2 weeks ago with this base code (wasn't working with meteor for 6+ months) and just updated to the current TS2 version. I want to mention that the scss file

**angular2-meteor-base/client/imports/app/app.component.scss**

should be in **angular2-meteor-base/client/** as it was before or imported there in a main.scss file.

**Comment by dotansimha** [comment]
This is a tricky issue, for a few reasons:
- `client/main.scss` should exists and contain the main styles and aren't related to any Angular 2 Component (such as styles for body, html, etc). This file was missing and added now.
- Each @Component should have his own style file, and it should be imported to the Component source file (`.ts`) and then loaded into the Component with `styles` or `styleUrls`, in order to enjoy the full power of Angular 2 with styles encapsulation (you can read more about it [here](https://angular.io/docs/ts/latest/guide/component-styles.html))

Part of angular2-meteor package, is the angular2-css package which handles this issue.
