### ISSUE TITLE
Syntax error for test in VS Code

### ISSUE THREAD

**Issue by zh-wowtv** [bsliran/angular2-meteor-base#40]
![img_7664](https://cloud.githubusercontent.com/assets/18462946/19299632/2607d614-9088-11e6-829a-00eed3b86fe6.jpg)

Any idea? Thanks

**Comment by dotansimha** [comment]
Which plugins do you use in VSCode? 
VSCode has a lot of imports scanner and dependencies resolvers... 
Also, this might not relate directly to the Angular2-meteor boilerplate package, have you tried other Angular 2 projects with you current VSCode configuration? 

Please reopen if this issue is specific for our boilerplate. 

Thanks
