### ISSUE TITLE
Meteor CLI does not work in project directory

### ISSUE THREAD

**Issue by kildareflare** [bsliran/angular2-meteor-base#51]
I'm trying to follow this tutorial for building a whatsapp clone https://angular-meteor.com/tutorials/whatsapp2/meteor/setup.

I had some issues with meteor command not being recognised in bash; but have [resolved ](http://stackoverflow.com/questions/29111648/meteor-command-not-found)those.

However I am now stuck as the meteor command does not appear to work within the whatsapp project directory. When I try and run `meteor help` or  `meteor add mys:fonts` or `meteor add-platform android` for example it just hangs.

However I have found that I can run `meteor help` in any other directory above this one fine.

If however, I remove the `.meteor directory`, the  `meteor help` command works, but the others, fail (correctly?) as they do not recognise the folder as a meteor project.

Any ideas?

directory structure is:
```
/.meteor
/client
/node_modules
/server
package.json
...etc...
```

Running on Windows10 and the following Meteor version was installed.
METEOR@1.4.2.1

**Comment by dotansimha** [comment]
Might not relate directly to this boilerplate.
@kildareflare , please try with the latest version of this boilerplate, after updating Meteor to the latest version.

**Comment by Urigo** [comment]
@kildareflare we've updated the `angular-meteor-base` repository and got many more example apps here: https://github.com/Urigo/angular-meteor/tree/master/examples

We are also updating the Meteor CLI tutorial to follow all the new changes.

We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
