### ISSUE TITLE
Error on typings.d.ts

### ISSUE THREAD

**Issue by Jakino** [bsliran/angular2-meteor-base#56]
File typings.d.ts
Error on  line 33: `import { Mongo } from "meteor/mongo";`
Error :  Cannot find module 'meteor/mongo'

Tested on Atom and Visual Studio Code with a fresh install

**Comment by ghybs** [comment]
Hi,

Have you tried to install the latest Meteor typings definition available on the registry through `typings`, instead of `npm`'s `@types/meteor`?

The latter correctly provides definitions for global variables, while the former also defines the namespaces that are referenced by the `import` statements.

See: https://github.com/meteor-typings/meteor

```bash
$ npm install -g typings # if you do not have typings installed yet
$ typings install registry:env/meteor --global
```

Hope this helps.

**Comment by adrprado** [comment]
@ghybs, if typings definitions are required in a project, why the `typings` directory is included in the _.gitignore_ file?

**Comment by ghybs** [comment]
Hi @adrprado,

`typings` directory is similar to `node_modules`: it is automatically generated by `typings install` command, based on the `typings.json` project file. Therefore there is no need to commit that folder.

However there is currently no such `typings.json` configuration file in this angular2-meteor boilerplate.

If this solution proves to be working for enough people, then it might be interesting adding one, e.g. through submitting a PR I guess.

**Comment by ghybs** [comment]
Hi,

Here is a more elegant fix:
1. Add `meteor-typings` npm package: `$ meteor npm install --save-dev meteor-typings`
2. Replace the `@types/meteor` reference in `typings.d.ts` by `meteor-typings`: `/// <reference types="meteor-typings" />`

Now the declaration files (which include the necessary `meteor` namespaces) are directly fetched from npm instead of using typings registry and CLI.

Hope this helps.

**Comment by Urigo** [comment]
We've updated the repo to the latest and greatest.

We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
