### ISSUE TITLE
Unable to import npm packages using Meteor 1.4.3.1

### ISSUE THREAD

**Issue by nick-lehmann** [bsliran/angular2-meteor-base#59]
Described in an [issue](https://github.com/meteor/meteor/issues/8447) on the main Meteor repo

**Comment by Urigo** [comment]
We've updated the repo to the latest and greatest - everything should work now.

We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
