### ISSUE TITLE
Concerns regarding high CPU/memory

### ISSUE THREAD

**Issue by bouchepat** [bsliran/angular2-meteor-base#62]
Hello, 
 
I've been developing an app with meteor/angular 2 for few months now and noticed the Node CPU/memory are pretty high (CPU: ~75%, memory ~850MB). 
I downloaded this boiler app and noticed an average CPU ~30% and memory ~825MB. 
A basic meteor app average CPU ~%10.
All tests run on the same machine (Windows 10x64).
This is concerning to me and was wondering what should be an average for a large app and how to minimize the node CPU process?

Also gradually, the app has been taking more and more time to refresh in the browser on a simple code change. Now it takes almost 2 minutes to reload the app! Any ideas on how to investigate the issue?

Thanks.

**Comment by Urigo** [comment]
Hi @bouchepat 
A lot has changed that is suppose to help.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6 (which includes Node 8.8 which can be a big improvement for performance, memory and build times from the current Node 4).

And we've re-written the boilerplate app.

Please try the new versions and let me know if that solves your problems.
If not, please try to create an example and I'll be happy to go through it with you.

Thank you!
